-- +goose Up
CREATE TABLE short_urls (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id       TEXT NOT NULL UNIQUE,            -- idempotency anchor, generated by the gateway
    slug         TEXT UNIQUE,                     -- NULL until a generated slug is assigned
    original_url TEXT NOT NULL,
    api_key_id   UUID NOT NULL REFERENCES api_keys(id),
    webhook_url  TEXT NOT NULL,                   -- resolved at the gateway (request or key default)
    qr_object    TEXT,                            -- object storage key; NULLed by the sweeper
    status       TEXT NOT NULL DEFAULT 'pending', -- pending | processing | done | failed
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at   TIMESTAMPTZ,                     -- NULL means never expires
    hit_count    BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_short_urls_slug    ON short_urls(slug);
CREATE INDEX idx_short_urls_api_key ON short_urls(api_key_id);
CREATE INDEX idx_short_urls_status  ON short_urls(status);

-- +goose Down
DROP TABLE short_urls;
