package main

import (
	"fmt"
	"math"
	"os"
	"strings"
	"time"
)

// helmServices are the chart deployments whose resources block we override.
// pgbouncer is in this list because the chart deploys it; postgres/redis/minio
// are not in scope because the chart treats them as out-of-cluster Services.
var helmServices = []string{"api", "worker", "observer", "pgbouncer"}

// RenderHelm writes a Helm values overlay that pins per-deployment requests
// and limits to the same numbers used for compose, and mirrors worker's
// max_replicas into keda.worker.maxReplicas so the autoscaler ceiling
// matches the budget.
//
// Use as a -f overlay on the canonical values.yaml:
//
//	helm install shortlink ./deploy/k8s \
//	     -f deploy/k8s/values.yaml -f deploy/k8s/values-local.yaml
func RenderHelm(cfg *Config, path string) error {
	var b strings.Builder
	b.WriteString("# AUTOGENERATED by cmd/limits render at " + time.Now().UTC().Format(time.RFC3339) + "\n")
	b.WriteString("# Edit config/local-limits.yaml and re-run scripts/local-setup -- do not edit this file.\n")
	b.WriteString("# Use as a -f overlay on deploy/k8s/values.yaml:\n")
	b.WriteString("#   helm install shortlink ./deploy/k8s -f deploy/k8s/values.yaml -f deploy/k8s/values-local.yaml\n\n")

	for _, n := range helmServices {
		s, ok := cfg.Services[n]
		if !ok {
			continue
		}
		replicas := s.MaxReplicas
		if replicas == 0 {
			replicas = 1
		}
		fmt.Fprintf(&b, "%s:\n", n)
		fmt.Fprintf(&b, "  replicas: %d\n", replicas)
		b.WriteString("  resources:\n")
		b.WriteString("    requests:\n")
		fmt.Fprintf(&b, "      cpu: %q\n", milliCPU(s.CPU))
		fmt.Fprintf(&b, "      memory: %s\n", mebibytes(s.MemoryMB))
		b.WriteString("    limits:\n")
		fmt.Fprintf(&b, "      cpu: %q\n", milliCPU(s.CPU))
		fmt.Fprintf(&b, "      memory: %s\n", mebibytes(s.MemoryMB))
		b.WriteString("\n")
	}

	// Mirror worker's max_replicas into KEDA's maxReplicas so the autoscaler
	// respects the same ceiling. KEDA itself stays enabled per values.yaml.
	// When max_replicas is unset, fall back to the same default the replicas
	// line uses (1) — emitting nothing here would let the chart's KEDA
	// default exceed the budget intent, which the audit flagged as asymmetric.
	if w, ok := cfg.Services["worker"]; ok {
		maxReplicas := w.MaxReplicas
		if maxReplicas <= 0 {
			maxReplicas = 1
		}
		b.WriteString("keda:\n")
		b.WriteString("  worker:\n")
		fmt.Fprintf(&b, "    maxReplicas: %d\n", maxReplicas)
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// milliCPU converts 0.5 -> "500m", 1.0 -> "1000m" (k8s convention).
// Uses math.Round so the helm output matches the compose renderer's
// `%.3f`+trim formatting at fractional CPU values (e.g. 0.1235 cores
// renders 124m here and "0.124" in compose, instead of the prior 123m
// floor that drifted by 1mC under truncation).
func milliCPU(f float64) string {
	return fmt.Sprintf("%dm", int(math.Round(f*1000)))
}

// mebibytes formats an integer MB as a Mi suffix (k8s convention).
func mebibytes(mb int) string {
	return fmt.Sprintf("%dMi", mb)
}
