package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// composeServiceMap maps logical service names in local-limits.yaml to the
// service names docker-compose.yml defines. They line up 1:1 today but
// keeping the mapping explicit makes future renames safe and documents
// which entries are compose-scoped vs k8s-only.
//
// Host binaries (api/worker/observer/loadtest) aren't compose services
// until Phase 4 ships --container-mode; their limits live in the config
// and feed validation, but the compose overlay leaves them out.
var composeServiceMap = map[string]string{
	"postgres":   "postgres",
	"redis":      "redis",
	"minio":      "minio",
	"pgbouncer":  "pgbouncer",
	"prometheus": "prometheus",
	"grafana":    "grafana",
}

// RenderCompose writes a Compose v3.x overlay that pins each backing service's
// CPU and memory under deploy.resources.limits. The docker compose CLI honors
// this block in non-swarm mode since v2.x.
//
// Output is sorted alphabetically and prefixed with a generated-on header so
// the file is diff-friendly and stays out of "did I edit this?" doubt.
func RenderCompose(cfg *Config, path string) error {
	var b strings.Builder
	b.WriteString("# AUTOGENERATED by cmd/limits render at " + time.Now().UTC().Format(time.RFC3339) + "\n")
	b.WriteString("# Edit config/local-limits.yaml and re-run scripts/local-setup -- do not edit this file.\n")
	b.WriteString("services:\n")

	var names []string
	for n := range composeServiceMap {
		if _, ok := cfg.Services[n]; ok {
			names = append(names, n)
		}
	}
	sort.Strings(names)

	for _, n := range names {
		s := cfg.Services[n]
		fmt.Fprintf(&b, "  %s:\n", composeServiceMap[n])
		b.WriteString("    deploy:\n")
		b.WriteString("      resources:\n")
		b.WriteString("        limits:\n")
		fmt.Fprintf(&b, "          cpus: \"%s\"\n", trimZero(s.CPU))
		fmt.Fprintf(&b, "          memory: %dM\n", s.MemoryMB)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// trimZero formats a float without trailing zeros (0.5 -> "0.5", 1.0 -> "1").
func trimZero(f float64) string {
	s := fmt.Sprintf("%.3f", f)
	s = strings.TrimRight(s, "0")
	s = strings.TrimRight(s, ".")
	return s
}
