apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shortlink.componentName" (dict "root" . "component" "secrets") }}
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "shortlink.databaseURL" . | quote }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  OBSERVER_INGEST_TOKEN: {{ .Values.secrets.observerIngestToken | quote }}
