// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT COUNT(*) FROM api_keys WHERE revoked_at IS NULL
`

// Used by `keygen --replace` to print "about to revoke N key(s)" before the
// operator confirms. A non-zero count against a DSN they didn't expect is
// the load-bearing signal that they're pointed at the wrong cluster.
func (q *Queries) CountActiveAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, key_hint, name, tier, webhook_secret, webhook_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key_hash, key_hint, name, tier, webhook_secret, webhook_url, created_at, revoked_at, last_used_at
`

type CreateAPIKeyParams struct {
	KeyHash       string      `json:"key_hash"`
	KeyHint       string      `json:"key_hint"`
	Name          string      `json:"name"`
	Tier          string      `json:"tier"`
	WebhookSecret string      `json:"webhook_secret"`
	WebhookUrl    pgtype.Text `json:"webhook_url"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.KeyHash,
		arg.KeyHint,
		arg.Name,
		arg.Tier,
		arg.WebhookSecret,
		arg.WebhookUrl,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Name,
		&i.Tier,
		&i.WebhookSecret,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_hash, key_hint, name, tier, webhook_secret, webhook_url, created_at, revoked_at, last_used_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

// Returns the key only if it exists and has not been revoked; a missing or
// revoked key both yield pgx.ErrNoRows, which the gateway maps to 401.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Name,
		&i.Tier,
		&i.WebhookSecret,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, key_hash, key_hint, name, tier, webhook_secret, webhook_url, created_at, revoked_at, last_used_at FROM api_keys WHERE id = $1
`

// Used by the webhook-delivery job to recover the per-key signing secret and
// key hint from the short_urls row's api_key_id.
func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Name,
		&i.Tier,
		&i.WebhookSecret,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeAPIKeyByHint = `-- name: RevokeAPIKeyByHint :execrows
UPDATE api_keys SET revoked_at = NOW()
WHERE key_hint = $1 AND revoked_at IS NULL
`

// Soft-delete used by the operator UI when removing a key. NOW()-stamps
// revoked_at so existing requests authenticated under this key keep
// working until they finish, while every subsequent GetAPIKeyByHash (which
// filters on revoked_at IS NULL) yields ErrNoRows. The validator cache's
// 60-second TTL is the upper bound on how long a revoked key still
// authenticates after the click. The hint guard avoids a UI accidentally
// revoking by id and racing with concurrent operator actions.
func (q *Queries) RevokeAPIKeyByHint(ctx context.Context, keyHint string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKeyByHint, keyHint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllActiveAPIKeys = `-- name: RevokeAllActiveAPIKeys :execrows
UPDATE api_keys SET revoked_at = NOW()
WHERE revoked_at IS NULL
`

// Bulk soft-delete used by `keygen --replace` to clear every still-active key
// before inserting the fresh tier batch. Without this, re-running keygen left
// old hashes valid in the DB even though keys.yaml on disk had moved on, so
// a previously-leaked raw key would keep authenticating until manually
// revoked. Matches RevokeAPIKeyByHint's NOW()-stamp semantics so in-flight
// requests under the revoked keys keep working until they finish.
func (q *Queries) RevokeAllActiveAPIKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllActiveAPIKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLastUsedAt = `-- name: UpdateLastUsedAt :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1 AND revoked_at IS NULL
`

// Bumps last_used_at; the gateway throttles how often this runs via a Redis
// marker (SPEC §9 / LAST_USED_THROTTLE). The revoked_at IS NULL guard
// prevents the async toucher from bumping a key that was revoked between
// the request's auth check and the touch goroutine actually firing —
// otherwise a revoked key would show a fresh last_used_at in admin views,
// confusing audit trails.
func (q *Queries) UpdateLastUsedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastUsedAt, id)
	return err
}
