// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, key_hint, name, tier, webhook_secret, webhook_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key_hash, key_hint, name, tier, webhook_secret, webhook_url, created_at, revoked_at, last_used_at
`

type CreateAPIKeyParams struct {
	KeyHash       string      `json:"key_hash"`
	KeyHint       string      `json:"key_hint"`
	Name          string      `json:"name"`
	Tier          string      `json:"tier"`
	WebhookSecret string      `json:"webhook_secret"`
	WebhookUrl    pgtype.Text `json:"webhook_url"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.KeyHash,
		arg.KeyHint,
		arg.Name,
		arg.Tier,
		arg.WebhookSecret,
		arg.WebhookUrl,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Name,
		&i.Tier,
		&i.WebhookSecret,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_hash, key_hint, name, tier, webhook_secret, webhook_url, created_at, revoked_at, last_used_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

// Returns the key only if it exists and has not been revoked; a missing or
// revoked key both yield pgx.ErrNoRows, which the gateway maps to 401.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Name,
		&i.Tier,
		&i.WebhookSecret,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, key_hash, key_hint, name, tier, webhook_secret, webhook_url, created_at, revoked_at, last_used_at FROM api_keys WHERE id = $1
`

// Used by the webhook-delivery job to recover the per-key signing secret and
// key hint from the short_urls row's api_key_id.
func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Name,
		&i.Tier,
		&i.WebhookSecret,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}
