// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertHit = `-- name: InsertHit :exec
INSERT INTO hits (slug, country, device)
VALUES ($1, $2, $3)
`

type InsertHitParams struct {
	Slug    string      `json:"slug"`
	Country pgtype.Text `json:"country"`
	Device  pgtype.Text `json:"device"`
}

func (q *Queries) InsertHit(ctx context.Context, arg InsertHitParams) error {
	_, err := q.db.Exec(ctx, insertHit, arg.Slug, arg.Country, arg.Device)
	return err
}
