// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID            pgtype.UUID        `json:"id"`
	KeyHash       string             `json:"key_hash"`
	KeyHint       string             `json:"key_hint"`
	Name          string             `json:"name"`
	Tier          string             `json:"tier"`
	WebhookSecret string             `json:"webhook_secret"`
	WebhookUrl    pgtype.Text        `json:"webhook_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
}

type Hit struct {
	ID         int64              `json:"id"`
	Slug       string             `json:"slug"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Country    pgtype.Text        `json:"country"`
	Device     pgtype.Text        `json:"device"`
}

type ShortUrl struct {
	ID          pgtype.UUID        `json:"id"`
	JobID       string             `json:"job_id"`
	Slug        pgtype.Text        `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	WebhookUrl  string             `json:"webhook_url"`
	QrObject    pgtype.Text        `json:"qr_object"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	HitCount    int64              `json:"hit_count"`
}
