// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Atomically transition pending -> processing. Zero rows means another worker
	// already claimed it (or it is no longer pending); the caller branches on the
	// row's current status. The lease-based re-claim of stale rows arrives in M2.
	ClaimShortURL(ctx context.Context, jobID string) (ShortUrl, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	FailShortURL(ctx context.Context, jobID string) (int64, error)
	// Write the assigned slug + QR object key and mark the job done. A unique
	// violation on slug surfaces as an error so the worker can regenerate.
	FinalizeShortURL(ctx context.Context, arg FinalizeShortURLParams) (int64, error)
	// Returns the key only if it exists and has not been revoked; a missing or
	// revoked key both yield pgx.ErrNoRows, which the gateway maps to 401.
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	// Used by the webhook-delivery job to recover the per-key signing secret and
	// key hint from the short_urls row's api_key_id.
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	// The redirect path: only rows that are finalized and unexpired resolve;
	// anything else yields pgx.ErrNoRows, which the handler maps to 404.
	GetActiveShortURLBySlug(ctx context.Context, slug pgtype.Text) (ShortUrl, error)
	GetShortURLByJobID(ctx context.Context, jobID string) (ShortUrl, error)
	IncrementHitCount(ctx context.Context, slug pgtype.Text) error
	InsertHit(ctx context.Context, arg InsertHitParams) error
	// Generated-slug path: slug stays NULL until the worker assigns one.
	InsertPendingShortURL(ctx context.Context, arg InsertPendingShortURLParams) (pgtype.UUID, error)
	// Custom-slug path: the slug is reserved at insert time. ON CONFLICT DO NOTHING
	// makes the reservation race-free — zero rows returned means the slug is taken
	// and the gateway responds 409.
	InsertPendingShortURLWithSlug(ctx context.Context, arg InsertPendingShortURLWithSlugParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
