// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Atomically transition a row to processing. Matches any pending or processing
	// row: asynq never delivers a task to two workers at once, so a processing row
	// is always this job's own prior attempt or a crashed worker — either way this
	// attempt takes over. The returned updated_at is the lease token guarding
	// finalize/fail; a stalled worker preempted by a re-claim fails that guard.
	ClaimShortURL(ctx context.Context, jobID string) (ShortUrl, error)
	// Bulk variant used by the sweeper: NULLs qr_object for many job_ids in one
	// statement instead of N round-trips. Order vs storage delete is unchanged:
	// the column is cleared first so a concurrent webhook handler can't Stat
	// a key we're about to delete.
	ClearQRObjects(ctx context.Context, jobIds []string) error
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	DeleteOldFailedShortURLs(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	// Abandoned pending/processing rows past SWEEP_STALE_AGE. Deleting a row frees
	// any custom slug it had reserved.
	DeleteStaleReservations(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	// Lease-guarded, same as finalize: a preempted worker cannot stamp 'failed'
	// over a row another worker is actively re-processing.
	FailShortURL(ctx context.Context, arg FailShortURLParams) (int64, error)
	// Lease-guarded: zero rows means the lease was lost to a re-claim, so a stalled
	// worker's late finalize is harmlessly discarded. A unique violation on slug
	// surfaces as an error so the worker can regenerate.
	FinalizeShortURL(ctx context.Context, arg FinalizeShortURLParams) (int64, error)
	// Returns the key only if it exists and has not been revoked; a missing or
	// revoked key both yield pgx.ErrNoRows, which the gateway maps to 401.
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	// Used by the webhook-delivery job to recover the per-key signing secret and
	// key hint from the short_urls row's api_key_id.
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	// The redirect path: only rows that are finalized and unexpired resolve;
	// anything else yields pgx.ErrNoRows, which the handler maps to 404.
	GetActiveShortURLBySlug(ctx context.Context, slug pgtype.Text) (ShortUrl, error)
	GetShortURLByJobID(ctx context.Context, jobID string) (ShortUrl, error)
	// Generated-slug path: slug stays NULL until the worker assigns one.
	InsertPendingShortURL(ctx context.Context, arg InsertPendingShortURLParams) (pgtype.UUID, error)
	// Custom-slug path: the slug is reserved at insert time. ON CONFLICT DO NOTHING
	// makes the reservation race-free — zero rows returned means the slug is taken
	// and the gateway responds 409.
	InsertPendingShortURLWithSlug(ctx context.Context, arg InsertPendingShortURLWithSlugParams) (pgtype.UUID, error)
	// done rows whose QR object has outlived QR_OBJECT_TTL and is still present.
	ListExpiredQRObjects(ctx context.Context, arg ListExpiredQRObjectsParams) ([]ListExpiredQRObjectsRow, error)
	// Single round-trip per redirect: inserts the hits row and bumps the
	// short_urls counter in one statement (the CTE runs the insert; the outer
	// UPDATE bumps the counter). Replaces the prior InsertHit + IncrementHitCount
	// pair, halving the PG round-trips on the redirect path. Named params dodge
	// the slug-column ambiguity between hits.slug and short_urls.slug.
	RecordHit(ctx context.Context, arg RecordHitParams) error
	// Bumps last_used_at; the gateway throttles how often this runs via a Redis
	// marker (SPEC §9 / LAST_USED_THROTTLE). The revoked_at IS NULL guard
	// prevents the async toucher from bumping a key that was revoked between
	// the request's auth check and the touch goroutine actually firing —
	// otherwise a revoked key would show a fresh last_used_at in admin views,
	// confusing audit trails.
	UpdateLastUsedAt(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
