// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_urls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimShortURL = `-- name: ClaimShortURL :one
UPDATE short_urls
SET status = 'processing', updated_at = NOW()
WHERE job_id = $1 AND status = 'pending'
RETURNING id, job_id, slug, original_url, api_key_id, webhook_url, qr_object, status, created_at, updated_at, expires_at, hit_count
`

// Atomically transition pending -> processing. Zero rows means another worker
// already claimed it (or it is no longer pending); the caller branches on the
// row's current status. The lease-based re-claim of stale rows arrives in M2.
func (q *Queries) ClaimShortURL(ctx context.Context, jobID string) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, claimShortURL, jobID)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Slug,
		&i.OriginalUrl,
		&i.ApiKeyID,
		&i.WebhookUrl,
		&i.QrObject,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.HitCount,
	)
	return i, err
}

const failShortURL = `-- name: FailShortURL :execrows
UPDATE short_urls
SET status = 'failed', updated_at = NOW()
WHERE job_id = $1
`

func (q *Queries) FailShortURL(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.Exec(ctx, failShortURL, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeShortURL = `-- name: FinalizeShortURL :execrows
UPDATE short_urls
SET slug = $2, qr_object = $3, status = 'done', updated_at = NOW()
WHERE job_id = $1
`

type FinalizeShortURLParams struct {
	JobID    string      `json:"job_id"`
	Slug     pgtype.Text `json:"slug"`
	QrObject pgtype.Text `json:"qr_object"`
}

// Write the assigned slug + QR object key and mark the job done. A unique
// violation on slug surfaces as an error so the worker can regenerate.
func (q *Queries) FinalizeShortURL(ctx context.Context, arg FinalizeShortURLParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeShortURL, arg.JobID, arg.Slug, arg.QrObject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveShortURLBySlug = `-- name: GetActiveShortURLBySlug :one
SELECT id, job_id, slug, original_url, api_key_id, webhook_url, qr_object, status, created_at, updated_at, expires_at, hit_count FROM short_urls
WHERE slug = $1
  AND status = 'done'
  AND (expires_at IS NULL OR expires_at > NOW())
`

// The redirect path: only rows that are finalized and unexpired resolve;
// anything else yields pgx.ErrNoRows, which the handler maps to 404.
func (q *Queries) GetActiveShortURLBySlug(ctx context.Context, slug pgtype.Text) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getActiveShortURLBySlug, slug)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Slug,
		&i.OriginalUrl,
		&i.ApiKeyID,
		&i.WebhookUrl,
		&i.QrObject,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.HitCount,
	)
	return i, err
}

const getShortURLByJobID = `-- name: GetShortURLByJobID :one
SELECT id, job_id, slug, original_url, api_key_id, webhook_url, qr_object, status, created_at, updated_at, expires_at, hit_count FROM short_urls WHERE job_id = $1
`

func (q *Queries) GetShortURLByJobID(ctx context.Context, jobID string) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getShortURLByJobID, jobID)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Slug,
		&i.OriginalUrl,
		&i.ApiKeyID,
		&i.WebhookUrl,
		&i.QrObject,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.HitCount,
	)
	return i, err
}

const incrementHitCount = `-- name: IncrementHitCount :exec
UPDATE short_urls SET hit_count = hit_count + 1 WHERE slug = $1
`

func (q *Queries) IncrementHitCount(ctx context.Context, slug pgtype.Text) error {
	_, err := q.db.Exec(ctx, incrementHitCount, slug)
	return err
}

const insertPendingShortURL = `-- name: InsertPendingShortURL :one
INSERT INTO short_urls (job_id, original_url, api_key_id, webhook_url, expires_at, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id
`

type InsertPendingShortURLParams struct {
	JobID       string             `json:"job_id"`
	OriginalUrl string             `json:"original_url"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	WebhookUrl  string             `json:"webhook_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Generated-slug path: slug stays NULL until the worker assigns one.
func (q *Queries) InsertPendingShortURL(ctx context.Context, arg InsertPendingShortURLParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPendingShortURL,
		arg.JobID,
		arg.OriginalUrl,
		arg.ApiKeyID,
		arg.WebhookUrl,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPendingShortURLWithSlug = `-- name: InsertPendingShortURLWithSlug :one
INSERT INTO short_urls (job_id, slug, original_url, api_key_id, webhook_url, expires_at, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
ON CONFLICT (slug) DO NOTHING
RETURNING id
`

type InsertPendingShortURLWithSlugParams struct {
	JobID       string             `json:"job_id"`
	Slug        pgtype.Text        `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	WebhookUrl  string             `json:"webhook_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Custom-slug path: the slug is reserved at insert time. ON CONFLICT DO NOTHING
// makes the reservation race-free — zero rows returned means the slug is taken
// and the gateway responds 409.
func (q *Queries) InsertPendingShortURLWithSlug(ctx context.Context, arg InsertPendingShortURLWithSlugParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPendingShortURLWithSlug,
		arg.JobID,
		arg.Slug,
		arg.OriginalUrl,
		arg.ApiKeyID,
		arg.WebhookUrl,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
