// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_urls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimShortURL = `-- name: ClaimShortURL :one
UPDATE short_urls
SET status = 'processing', updated_at = NOW()
WHERE job_id = $1 AND status IN ('pending', 'processing')
RETURNING id, job_id, slug, original_url, api_key_id, webhook_url, qr_object, status, created_at, updated_at, expires_at, hit_count
`

// Atomically transition a row to processing. Matches any pending or processing
// row: asynq never delivers a task to two workers at once, so a processing row
// is always this job's own prior attempt or a crashed worker — either way this
// attempt takes over. The returned updated_at is the lease token guarding
// finalize/fail; a stalled worker preempted by a re-claim fails that guard.
func (q *Queries) ClaimShortURL(ctx context.Context, jobID string) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, claimShortURL, jobID)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Slug,
		&i.OriginalUrl,
		&i.ApiKeyID,
		&i.WebhookUrl,
		&i.QrObject,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.HitCount,
	)
	return i, err
}

const clearQRObjects = `-- name: ClearQRObjects :exec
UPDATE short_urls SET qr_object = NULL WHERE job_id = ANY($1::text[])
`

// Bulk variant used by the sweeper: NULLs qr_object for many job_ids in one
// statement instead of N round-trips. Order vs storage delete is unchanged:
// the column is cleared first so a concurrent webhook handler can't Stat
// a key we're about to delete.
func (q *Queries) ClearQRObjects(ctx context.Context, jobIds []string) error {
	_, err := q.db.Exec(ctx, clearQRObjects, jobIds)
	return err
}

const deleteOldFailedShortURLs = `-- name: DeleteOldFailedShortURLs :execrows
DELETE FROM short_urls
WHERE status = 'failed' AND updated_at < $1
`

func (q *Queries) DeleteOldFailedShortURLs(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldFailedShortURLs, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingReservation = `-- name: DeletePendingReservation :execrows
DELETE FROM short_urls
WHERE job_id = $1 AND status = 'pending'
`

// Targeted rollback when the gateway inserted a pending row but then failed
// to enqueue the job. Pending-only guard so a worker that beat us to claim
// the row (shouldn't happen — Enqueue failed — but defense in depth) doesn't
// have its in-flight processing row yanked out from under it. Frees any
// reserved custom slug immediately, so the client can retry without waiting
// for SWEEP_STALE_AGE.
func (q *Queries) DeletePendingReservation(ctx context.Context, jobID string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingReservation, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleReservations = `-- name: DeleteStaleReservations :execrows
DELETE FROM short_urls
WHERE status IN ('pending', 'processing') AND updated_at < $1
`

// Abandoned pending/processing rows past SWEEP_STALE_AGE. Deleting a row frees
// any custom slug it had reserved.
func (q *Queries) DeleteStaleReservations(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleReservations, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failShortURL = `-- name: FailShortURL :execrows
UPDATE short_urls
SET status = 'failed', updated_at = NOW()
WHERE job_id = $1 AND updated_at = $2
`

type FailShortURLParams struct {
	JobID string             `json:"job_id"`
	Lease pgtype.Timestamptz `json:"lease"`
}

// Lease-guarded, same as finalize: a preempted worker cannot stamp 'failed'
// over a row another worker is actively re-processing.
func (q *Queries) FailShortURL(ctx context.Context, arg FailShortURLParams) (int64, error) {
	result, err := q.db.Exec(ctx, failShortURL, arg.JobID, arg.Lease)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeShortURL = `-- name: FinalizeShortURL :execrows
UPDATE short_urls
SET slug = $1, qr_object = $2, status = 'done', updated_at = NOW()
WHERE job_id = $3 AND updated_at = $4
`

type FinalizeShortURLParams struct {
	Slug     pgtype.Text        `json:"slug"`
	QrObject pgtype.Text        `json:"qr_object"`
	JobID    string             `json:"job_id"`
	Lease    pgtype.Timestamptz `json:"lease"`
}

// Lease-guarded: zero rows means the lease was lost to a re-claim, so a stalled
// worker's late finalize is harmlessly discarded. A unique violation on slug
// surfaces as an error so the worker can regenerate.
func (q *Queries) FinalizeShortURL(ctx context.Context, arg FinalizeShortURLParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeShortURL,
		arg.Slug,
		arg.QrObject,
		arg.JobID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveShortURLBySlug = `-- name: GetActiveShortURLBySlug :one
SELECT id, job_id, slug, original_url, api_key_id, webhook_url, qr_object, status, created_at, updated_at, expires_at, hit_count FROM short_urls
WHERE slug = $1
  AND status = 'done'
  AND (expires_at IS NULL OR expires_at > NOW())
`

// The redirect path: only rows that are finalized and unexpired resolve;
// anything else yields pgx.ErrNoRows, which the handler maps to 404.
func (q *Queries) GetActiveShortURLBySlug(ctx context.Context, slug pgtype.Text) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getActiveShortURLBySlug, slug)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Slug,
		&i.OriginalUrl,
		&i.ApiKeyID,
		&i.WebhookUrl,
		&i.QrObject,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.HitCount,
	)
	return i, err
}

const getShortURLByJobID = `-- name: GetShortURLByJobID :one
SELECT id, job_id, slug, original_url, api_key_id, webhook_url, qr_object, status, created_at, updated_at, expires_at, hit_count FROM short_urls WHERE job_id = $1
`

func (q *Queries) GetShortURLByJobID(ctx context.Context, jobID string) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getShortURLByJobID, jobID)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Slug,
		&i.OriginalUrl,
		&i.ApiKeyID,
		&i.WebhookUrl,
		&i.QrObject,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.HitCount,
	)
	return i, err
}

const insertPendingShortURL = `-- name: InsertPendingShortURL :one
INSERT INTO short_urls (job_id, original_url, api_key_id, webhook_url, expires_at, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id
`

type InsertPendingShortURLParams struct {
	JobID       string             `json:"job_id"`
	OriginalUrl string             `json:"original_url"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	WebhookUrl  string             `json:"webhook_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Generated-slug path: slug stays NULL until the worker assigns one.
func (q *Queries) InsertPendingShortURL(ctx context.Context, arg InsertPendingShortURLParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPendingShortURL,
		arg.JobID,
		arg.OriginalUrl,
		arg.ApiKeyID,
		arg.WebhookUrl,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPendingShortURLWithSlug = `-- name: InsertPendingShortURLWithSlug :one
INSERT INTO short_urls (job_id, slug, original_url, api_key_id, webhook_url, expires_at, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
ON CONFLICT (slug) DO NOTHING
RETURNING id
`

type InsertPendingShortURLWithSlugParams struct {
	JobID       string             `json:"job_id"`
	Slug        pgtype.Text        `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	WebhookUrl  string             `json:"webhook_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Custom-slug path: the slug is reserved at insert time. ON CONFLICT DO NOTHING
// makes the reservation race-free — zero rows returned means the slug is taken
// and the gateway responds 409.
func (q *Queries) InsertPendingShortURLWithSlug(ctx context.Context, arg InsertPendingShortURLWithSlugParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPendingShortURLWithSlug,
		arg.JobID,
		arg.Slug,
		arg.OriginalUrl,
		arg.ApiKeyID,
		arg.WebhookUrl,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listExpiredQRObjects = `-- name: ListExpiredQRObjects :many
SELECT job_id, qr_object FROM short_urls
WHERE status = 'done' AND qr_object IS NOT NULL AND updated_at < $1
LIMIT $2
`

type ListExpiredQRObjectsParams struct {
	Cutoff  pgtype.Timestamptz `json:"cutoff"`
	MaxRows int32              `json:"max_rows"`
}

type ListExpiredQRObjectsRow struct {
	JobID    string      `json:"job_id"`
	QrObject pgtype.Text `json:"qr_object"`
}

// done rows whose QR object has outlived QR_OBJECT_TTL and is still present.
func (q *Queries) ListExpiredQRObjects(ctx context.Context, arg ListExpiredQRObjectsParams) ([]ListExpiredQRObjectsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredQRObjects, arg.Cutoff, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredQRObjectsRow{}
	for rows.Next() {
		var i ListExpiredQRObjectsRow
		if err := rows.Scan(&i.JobID, &i.QrObject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
